version: "3"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  backend:
    build: ./flask
    ports:
      - "8080:8080"
    env_file: ./flask/.env
